apiVersion: apps/v1
kind: Deployment
metadata:
  name: ravishop-ai
  namespace: default
  labels:
    app: ravishop-ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ravishop-ai
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ravishop-ai
    spec:
      containers:
        - name: ravishop-ai
          image: 973877242361.dkr.ecr.ap-south-1.amazonaws.com/ravishop-ai:latest
          ports:
            - containerPort: 5000
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: ravishop-config
                  key: APP_NAME
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: ravishop-config
                  key: APP_ENV
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: ravishop-config
                  key: APP_PORT
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
