apiVersion: v1
kind: Service
metadata:
  name: ravishop-ai-service
  namespace: default
  labels:
    app: ravishop-ai
spec:
  selector:
    app: ravishop-ai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
